services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    AdrianBaez\Bundle\MarkdownBundle\Helper: ~
    AdrianBaez\Bundle\MarkdownBundle\Markdown: ~

    AdrianBaez\Bundle\MarkdownBundle\Interfaces\MarkdownInterface: '@AdrianBaez\Bundle\MarkdownBundle\Markdown'

    adrianbaez.markdown:
        alias: AdrianBaez\Bundle\MarkdownBundle\Markdown
        public: true
